### ISSUE TITLE
uhs file inputs not being uploaded to the containers in docker-dev03 server

### ISSUE THREAD

**Issue by sum1lim** [pacificclimate/osprey#74]
**Describe the bug**
After the multi-stage build strategy is applied, the test data can no longer be found from the Docker image, and it revealed an issue that hasn't been identified. It seems like the uhs file inputs used for `wps_convert` are not uploaded to the Docker container in the Docker server, thus the following messages are produced. 
```
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/pywps/app/Process.py", line 249, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/root/.local/lib/python3.8/site-packages/osprey/processes/wps_convert.py", line 128, in _handler
    convert(config_file)
  File "/root/.local/lib/python3.8/site-packages/rvic/convert.py", line 26, in convert
    dom_data, new_dom_data, outlets, config_dict, directories = uhs2param_init(
  File "/root/.local/lib/python3.8/site-packages/rvic/convert.py", line 98, in uhs2param_init
    outlets = read_station_file(
  File "/root/.local/lib/python3.8/site-packages/rvic/core/convert.py", line 52, in read_station_file
    raise ValueError("missing uhs_file: (%s or %s)", uhs_file, uhs2_file)
ValueError: ('missing uhs_file: (%s or %s)', './tests/data/samples/sample.uh_s2', '/tmp/pywps_process_g6cj6wty/station.uh_s2')
2020-12-22 23:21:49 ERROR: osprey: Process error: method=wps_convert.py._handler, line=128, msg=('missing uhs_file: (%s or %s)', './tests/data/samples/sample.uh_s2', '/tmp/pywps_process_g6cj6wty/station.uh_s2')
```

**To Reproduce**
1. Run `test_notebooks_custom` with a container up'd using an image built after #73 
2. Check the log messages in the docker-dev03 server.

**Expected behavior**
Should pass the demo without failure.

**Comment by cairosanders** [comment]
Fixed in #83
